name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up the Java JDK
      uses: actions/setup-java@v2
      with:
        java-version: '18'
        distribution: 'adopt'
        
    - name: Set up the Gradle
      uses: gradle/gradle-build-action@v2.3.3
      with:
        gradle-version: '7.6'

    - name: Test, build with Gradle
      run: |
        gradle wrapper
        ./gradlew test
        ./gradlew clean build
